#!/usr/bin/env sh

CURRENTDIR=$(pwd)

# Absolute path to this script,
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in
SCRIPTPATH=$(dirname "$SCRIPT")

cd $SCRIPTPATH

# Build/Install
./gradlew :cli:installDist > /dev/null
# Start the shell
./cli/build/install/cli/bin/cli

cd $CURRENTDIR
