#!/usr/bin/env sh

# Absolute path to this script,
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in
SCRIPTPATH=$(dirname "$SCRIPT")

# Build/Install
sh -c $SCRIPTPATH/gradlew :cli:installDist > /dev/null
# Start the shell
sh -c $SCRIPTPATH/cli/build/install/cli/bin/cli
