package main

import (
	"github.com/alecthomas/chroma"
	"github.com/alecthomas/chroma/styles"
)

var style = styles.Register(chroma.MustNewStyle("dogbin", chroma.StyleEntries{
	chroma.Comment:                  "#7988b5",
	chroma.CommentHashbang:          "#7988b5",
	chroma.CommentMultiline:         "#7988b5",
	chroma.CommentPreproc:           "#97dbbe",
	chroma.CommentSingle:            "#7988b5",
	chroma.CommentSpecial:           "#7988b5",
	chroma.Generic:                  "#f8f2f7",
	chroma.GenericDeleted:           "#963f3f",
	chroma.GenericEmph:              "#f8f2f7 underline",
	chroma.GenericError:             "#eb1e3d",
	chroma.GenericHeading:           "#f8f2f7 bold",
	chroma.GenericInserted:          "#aee8b7 bold",
	chroma.GenericOutput:            "#44475a",
	chroma.GenericPrompt:            "#e0b8da",
	chroma.GenericStrong:            "#f8f2f7 bold",
	chroma.GenericSubheading:        "#f8f2f7 bold",
	chroma.GenericTraceback:         "#f0cee0",
	chroma.GenericUnderline:         "underline",
	chroma.Error:                    "#f07199",
	chroma.Keyword:                  "#97dbbe",
	chroma.KeywordConstant:          "#97dbbe bold",
	chroma.KeywordDeclaration:       "#bc89c9 italic",
	chroma.KeywordNamespace:         "#97dbbe",
	chroma.KeywordPseudo:            "#97dbbe",
	chroma.KeywordReserved:          "#97dbbe",
	chroma.KeywordType:              "#bc89c9",
	chroma.Literal:                  "#f8f2f7",
	chroma.LiteralDate:              "#dbc1d7",
	chroma.Name:                     "#f8f2f7",
	chroma.NameAttribute:            "#94d1a4",
	chroma.NameBuiltin:              "#bc89c9 italic",
	chroma.NameBuiltinPseudo:        "#f8f2f7",
	chroma.NameClass:                "#d1b0cc",
	chroma.NameConstant:             "#d1b0cc bold",
	chroma.NameDecorator:            "#d1b0cc",
	chroma.NameEntity:               "#d1b0cc",
	chroma.NameException:            "#d1b0cc",
	chroma.NameFunction:             "#f5da98",
	chroma.NameLabel:                "#bc89c9 italic",
	chroma.NameNamespace:            "#f8f2f7",
	chroma.NameOther:                "#f8f2f7",
	chroma.NameTag:                  "#97dbbe",
	chroma.NameVariable:             "#bc89c9 italic",
	chroma.NameVariableClass:        "#bc89c9 italic",
	chroma.NameVariableGlobal:       "#bc89c9 italic",
	chroma.NameVariableInstance:     "#bc89c9 italic",
	chroma.LiteralNumber:            "#bd93f9",
	chroma.LiteralNumberBin:         "#bd93f9",
	chroma.LiteralNumberFloat:       "#bd93f9",
	chroma.LiteralNumberHex:         "#bd93f9",
	chroma.LiteralNumberInteger:     "#bd93f9",
	chroma.LiteralNumberIntegerLong: "#bd93f9",
	chroma.LiteralNumberOct:         "#bd93f9",
	chroma.Operator:                 "#97dbbe",
	chroma.OperatorWord:             "#97dbbe",
	chroma.Other:                    "#f8f2f7",
	chroma.Punctuation:              "#f8f2f7",
	chroma.LiteralString:            "#f0a8c7",
	chroma.LiteralStringBacktick:    "#f0a8c7",
	chroma.LiteralStringChar:        "#d496b1",
	chroma.LiteralStringDoc:         "#f0a8c7",
	chroma.LiteralStringDouble:      "#f0a8c7",
	chroma.LiteralStringEscape:      "#f0a8c7",
	chroma.LiteralStringHeredoc:     "#f0a8c7",
	chroma.LiteralStringInterpol:    "#f0a8c7",
	chroma.LiteralStringOther:       "#f0a8c7",
	chroma.LiteralStringRegex:       "#f0a8c7",
	chroma.LiteralStringSingle:      "#f0a8c7",
	chroma.LiteralStringSymbol:      "#f0a8c7",
	chroma.Text:                     "#f8f2f7",
	chroma.TextWhitespace:           "#f8f2f7",
	chroma.Background:               " bg:#282a36",
}))
